### PR TITLE
Bor consensus implementation

### PR DESCRIPTION
**Pull request by 0xKrishna**
To build
```
make turbo
```

To run on mumbai
```
turbo-bor --chain=mumbai --bor.heimdall=https://heimdall.api.matic.today
```

### CODE REVIEW

**Comment by koen84** [comment]
@0xKrishna could you elaborate on the current status ?  (Especially given the label "help wanted".)
Also, i'd love to see this as a PR to the official erigon repo (eventually).

**Comment by 0xKrishna** [comment]
@koen84 The current status is that the node is able to sync but gives hash related error in stage [10/18 Intermediate Hash]
I am running a local node as of now on mumbai to check more on this.
The remaining work includes
- Implementing bor RPC methods
- Checking state sync txns are working fine
- Fix VerifyHeader in the Bor consensus, It's bypassed as of now because It required doing a contract call and I was not able to get the `sysCall` method there, See `Finalize` and `Prepare` for reference.
We might have to do more changes but these are the ones I can recall for now, Feel free to test using the commands given in PR Description.

**Comment by 0xKrishna** [comment]
This is the issue I got in my current node trying to sync on mumbai
```Nov 22 15:15:37 ip-192-168-0-172 bash[3410]: [EROR] [11-22|15:15:37.214] [9/16 IntermediateHashes] Wrong trie root of block 21778336: 82b13d17235610b6d9ecbe7e8fc9972c892748e52e12226faf887e60c369dd92, expected (fr
Nov 22 15:15:37 ip-192-168-0-172 bash[3410]: [WARN] [11-22|15:15:37.214] Unwinding due to incorrect root hash     to=10889198
Nov 22 15:15:37 ip-192-168-0-172 bash[3410]: [INFO] [11-22|15:15:37.214] UnwindTo                                 block=10889198 bad_block_hash=0x5ccf89a785f7ce7052ca111acd813442c3bec45e588369ecd20333e2e7e6eaa6
Nov 22 15:15:37 ip-192-168-0-172 bash[3410]: [INFO] [11-22|15:15:37.320] [9/16 IntermediateHashes] DONE           in=2m17.844008971s
Nov 22 15:15:37 ip-192-168-0-172 bash[3410]: [INFO] [11-22|15:15:37.320] [8/16 HashState] Unwinding started       from=21778336 to=10889198 storage=false codes=true```

**Comment by koen84** [comment]
Thanks for the update.  I would suggest checking [this PR for bsc](https://github.com/ledgerwatch/erigon/pull/2991), they are talking also about `sysCall`.  Many of those commenters are from Erigon team.

**Comment by 0xKrishna** [comment]
Thanks, @koen84 for pointing that out, I will take a look at that.
Currently, I am trying to fix the `Wrong trie root of block` issue
I found that it is happening due to span changing txn not properly processed by the node and state not getting updated.

**Pull request merged**
